server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: true
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  sql:
    init:
      schema-locations:
      - classpath:db/table.sql
      data-locations:
      - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  # 머스태치 사용할때 세션에 접근하게 해줌
  mustache: 
    servlet:
      expose-session-attributes: true
mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true